<?php
// $Id$
define('VOIP_MAX_SMS_INTERVAL' , 10);

/**
 * @file
 * Implementation of core functionality associated with voip calls
 */
/*
foreach (array(
           'voipscript.inc',
           'voipcall.inc',
           'voipsession.inc',
           'voipvoice.inc'
         ) as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}*/

module_load_include('inc', 'voipcall', 'voipscript');
module_load_include('inc', 'voipcall', 'voipcall');
module_load_include('inc', 'voipcall', 'voipsession');
module_load_include('inc', 'voipcall', 'voipvoice');

/**
 * Public functions
 */

/**
 * Implementation of hook_menu()
 */
function voipcall_menu() {
  $items = array();

  $items['admin/voip/call/settings'] = array(
    'title' => 'Default call configuration',
    'description' => 'Defines default parameters used in VoIP Drupal calls.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipcall_admin_form', NULL),
    'access arguments' => array('administer voipcall setup'),
  );

  $items['admin/voip/call/log'] = array(
    'title' => 'VoIP Call Log',
    'description' => 'Lists all VoIP Drupal calls.',
    'page callback' => 'voipcall_call_log',
    'access arguments' => array('administer voipcall setup'),
  );

  $items['admin/voip/session/log'] = array(
    'title' => 'VoIP Session Log',
    'description' => 'Lists all VoIP Drupal sessions.',
    'page callback' => 'voipcall_session_log',
    'access arguments' => array('administer voipcall setup'),
  );

  $items['voipcall/%'] = array(
    'title callback' => 'voipcall_call_page_title',
    'title arguments' => array(1),
    'description' => 'Lists individual VoIP Drupal calls.',
    'page callback' => 'voipcall_call_page',
    'page arguments' => array(1),
    'access arguments' => array('administer voipcall setup'),
  );

  $items['voipsession/delete/%'] = array(
    'title' => 'VoIP Delete Session',
    'description' => 'Delete voip session.',
    'page callback' => 'voipcall_session_delete',
    'page arguments' => array(2),
    'access arguments' => array('administer voipcall setup'),
  );

  $items['voip/sound/beep'] = array(
    'title' => 'Beep sound',
    'description' => 'Plays beep sound',
    'page callback' => 'voipcall_play_beep',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function voipcall_perm() {
  return array(
    'administer voipcall setup',
    'Use PHP input for VoIP Script (dangerous - grant with care)'
  );
}

/**
 * Implements hook_views_api().
 */
function voipcall_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'voipcall') . '/views',
  );
}

/**
 * Implementation of hook_block()
 */
function voipcall_block($op = 'list', $delta = 0, $edit = array()) {
  // listing of blocks, such as on the admin/block page
  if ($op == "list") {
    $blocks[1]['info'] = t('VoIP Drupal Default call configuration');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();
    if (user_access('administer voipcall setup')) {
      $block = array(
        'subject' => t('VoIP Drupal call configuration'),
        'content' => drupal_get_form('voipcall_block_form'),
      );
    }


    return $block;
  }
}

function voipcall_block_form() {

  $form['voipcall_inbound_call_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Inbound call script name'),
    '#description' => t('Script used for incoming phone calls'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_inbound_call_script_name', 'voipcall_default_inbound_call_script'),
  );

  $form['voipcall_outbound_call_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Outbound call script name'),
    '#description' => t('Script used for outgoing calls'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_outbound_call_script_name', 'voipcall_default_outbound_call_script'),
  );

  $form['voipcall_inbound_text_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Inbound text script name'),
    '#description' => t('Script used for incoming text messages'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_inbound_text_script_name', 'voipcall_default_inbound_text_script'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Validates the submission of the configuration form.
 */
function voipcall_block_form_validate($form, &$form_state) {
  $values = $form_state['values'];
// TODO: provide feedback directly on the affected fields...
  $script_name = $values['voipcall_inbound_call_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid inbound call script name: @script_name.', array('@script_name' => $script_name)));
  }
  $script_name = $values['voipcall_outbound_call_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid outbound call script name: @script_name.', array('@script_name' => $script_name)));
  }

  $script_name = $values['voipcall_inbound_text_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid inbound text script name: @script_name.', array('@script_name' => $script_name)));
  }
}


function voipcall_block_form_submit($form, &$form_state) {
  // Remove unecessary values
  //unset($form_state['values']['op'], $form_state['values']['submit'], $form_state['values']['form_token'], $form_state['values']['form_id']);
  // store values
  variable_set('voipcall_inbound_call_script_name', $form_state['values']['voipcall_inbound_call_script_name']);
  variable_set('voipcall_outbound_call_script_name', $form_state['values']['voipcall_outbound_call_script_name']);
  variable_set('voipcall_inbound_text_script_name', $form_state['values']['voipcall_inbound_text_script_name']);
  drupal_set_message(t('The default call settings have been saved.'));
}

/**
 * Form implementation
 */
function voipcall_admin_form() {
  $form['voipcall_cid_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Caller id name'),
    '#description' => t("Caller id name to be used in VoIP Drupal calls. Note that, in the U.S., this value is ignored and replaced by the caller name stored in the telecommunications service's database"),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('voipcall_cid_name', ''),
  );

  $form['voipcall_cid_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Caller id number'),
    '#description' => t('Caller id number to be used in VoIP Drupal calls.
    Number must be in <a target="_blank" href="http://en.wikipedia.org/wiki/E.164">E.164</a> format.
    Supported formats include:
    <ul>
    <li>tel: Phone Number - must be proceeded by a + and the country code (ie - +14155551212 for a US #)</li>
    <li>sip: SIP protocol address (ie - sip:username@domain.com)</li>
    </ul>
    '),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('voipcall_cid_number', ''),
    '#required' => TRUE,
  );

  $form['voipcall_text_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Text number'),
    '#description' => t('Default text number.  Only used if it is different from the Caller id number.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('voipcall_text_number', ''),
  );

  $form['voipcall_inbound_call_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Inbound call script name'),
    '#description' => t('Name of the dialplan script to be used whenever the system receives a phone call.'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_inbound_call_script_name', 'voipcall_default_inbound_call_script'),
  );

  $form['voipcall_outbound_call_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Outbound call script name'),
    '#description' => t('Name of the default dialplan script to be used in calls made by the system.'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_outbound_call_script_name', 'voipcall_default_outbound_call_script'),
  );

  $form['voipcall_inbound_text_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Inbound text script name'),
    '#description' => t('Name of the dialplan script to be used whenever the system receives a text message.'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_inbound_text_script_name', 'voipcall_default_inbound_text_script'),
  );

  /*$form['voipcall_outbound_text_script_name'] = array(
    '#type' => 'select',
    '#title' => t('Outbound text script name'),
    '#description' => t('Name of the dialplan script to be used whenever the system sends a text message.'),
    '#options' => VoipScript::getScriptNames(),
    '#default_value' => variable_get('voipcall_outbound_text_script_name', 'voipcall_default_outbound_text_script'),
  );*/


  if (module_exists('sms')) {
    $disabled = FALSE;
  }
  else {
    $disabled = TRUE;
  }

  $form['voipcall_accept_sms_framework'] = array(
    '#type' => 'checkbox',
    '#title' => t('Accept incoming text messages from the SMS framework'),
    '#default_value' => variable_get('voipcall_accept_sms_framework', 0),
    '#disabled' => $disabled,
  );

  $form['voipcall_use_sms_framework'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use SMS Framework for outgoing text messages'),
    '#description' => t('By default, SMS messages are sent via the default VoIP server. Check this option to use the Drupal SMS Framework instead.'),
    '#default_value' => variable_get('voipcall_use_sms_framework', 0),
    '#disabled' => $disabled,
  );

  $form['voipcall_default_text_handler'] = array(
    '#type' => 'textfield',
    '#title' => t('Default text message handler'),
    '#description' => t('Default message text handler. For example you can use voipcall_join_text_messages() which will join multiple SMS message segments back into one message.'),
    '#default_value' => variable_get('voipcall_default_text_handler', ''),
  );

  $form['voipcall_default_session_time'] = array(
    '#type' => 'textfield',
    '#title' => t('Default session duration'),
    '#description' => t('Default session duration time in seconds.'),
    '#default_value' => variable_get('voipcall_default_session_time', 0),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}


/**
 * Validates the submission of the configuration form.
 */
function voipcall_admin_form_validate($form, &$form_state) {
  $values = $form_state['values'];
// TODO: provide feedback directly on the affected fields...
  $script_name = $values['voipcall_inbound_call_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid inbound call script name: @script_name.', array('@script_name' => $script_name)));
  }
  $script_name = $values['voipcall_outbound_call_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid outbound call script name: @script_name.', array('@script_name' => $script_name)));
  }

  $script_name = $values['voipcall_inbound_text_script_name'];
  $script = VoipScript::loadScript($script_name);
  if (!$script) {
    form_set_error('', t('Invalid inbound text script name: @script_name.', array('@script_name' => $script_name)));
  }

  if ($values['voipcall_default_session_time'] < 0) {
    form_set_error('voipcall_default_session_time', t('Session duration time must be positive integer.'));
  }

  if ($values['voipcall_default_text_handler'] && !function_exists($values['voipcall_default_text_handler'])) {
    form_set_error('voipcall_default_text_handler', t('Invalid text handler function: @text_handler.', array('@text_handler' => $values['voipcall_default_text_handler'])));
  }
}

function voipcall_admin_form_submit($form, &$form_state) {

  // Remove unecessary values
  unset($form_state['values']['op'], $form_state['values']['submit'], $form_state['values']['form_token'], $form_state['values']['form_id']);

  // store values
  variable_set('voipcall_cid_name', $form_state['values']['voipcall_cid_name']);
  variable_set('voipcall_cid_number', $form_state['values']['voipcall_cid_number']);
  variable_set('voipcall_text_number', $form_state['values']['voipcall_text_number']);

  variable_set('voipcall_inbound_call_script_name', $form_state['values']['voipcall_inbound_call_script_name']);
  variable_set('voipcall_outbound_call_script_name', $form_state['values']['voipcall_outbound_call_script_name']);
  variable_set('voipcall_accept_sms_framework', $form_state['values']['voipcall_accept_sms_framework']);
  variable_set('voipcall_use_sms_framework', $form_state['values']['voipcall_use_sms_framework']);
  variable_set('voipcall_inbound_text_script_name', $form_state['values']['voipcall_inbound_text_script_name']);
  variable_set('voipcall_default_session_time', $form_state['values']['voipcall_default_session_time']);
  variable_set('voipcall_default_text_handler', $form_state['values']['voipcall_default_text_handler']);

  drupal_set_message(t('The default call settings have been saved.'));

  $form_state['redirect'] = 'admin/voip';
}

/*
 * Script-related functions
 */

/**
 * Return the name of the default script to be used with new incoming calls
 */
function voipcall_get_default_inbound_call_script_name() {
  $script_name = variable_get('voipcall_inbound_call_script_name', 'voipcall_default_inbound_call_script');
  return $script_name;
}

/**
 * Return the name of the default script to be used with new outgoing calls
 */
function voipcall_get_default_outbound_call_script_name() {
  $script_name = variable_get('voipcall_outbound_call_script_name', 'voipcall_default_outbound_call_script');
  return $script_name;
}

/**
 * Return the name of the default script to be used with incoming text messages
 */
function voipcall_get_default_inbound_text_script_name() {
  $script_name = variable_get('voipcall_inbound_text_script_name', 'voipcall_default_inbound_text_script');
  return $script_name;
}

/**
 * Implementation of hook_voipscript_get_script_names()
 */
function voipcall_voipscript_get_script_names() {
  $script_names[] = 'voipcall_default_inbound_call_script';
  $script_names[] = 'voipcall_default_outbound_call_script';
  $script_names[] = 'voipcall_default_inbound_text_script';

  return $script_names;
}


/**
 * Implementation of hook_voipscript_load_script()
 */
function voipcall_voipscript_load_script($script_name, $options = NULL) {
  $script = NULL;
  switch ($script_name) {
    default:
      break;
    case 'voipcall_default_inbound_call_script':
      $script = new VoipScript('voipcall_default_inbound_call_script');
      $script->addSay(t("Welcome to the VoIP Drupal platform!"));
      $script->addSay(t("Bye bye."));
      $script->addHangup();
      break;
    case 'voipcall_default_outbound_call_script':
      $script = new VoipScript('voipcall_default_outbound_call_script');
      $script->addSay(t("This is a call from the VoIP Drupal platform!"));
      $script->addSay(t("Bye bye."));
      $script->addHangup();
      break;
    case 'voipcall_default_inbound_text_script':
      $script = new VoipScript('voipcall_default_inbound_text_script');
      $script->addSendText(t("This is a TEXT response from the VoIP Drupal platform!"));
      break;
    case 'voipscript_run_ivr_menu':
      $script = voipscript_get_run_ivr_menu_script($options);
      break;
  }
  return $script;
}

/**
 * Implementation of hook_theme().
 */
function voipcall_theme() {
  return array(
    'voipcall_play_beep' => array(
      'arguments' => array(),
    ),
  );
}

function voipcall_play_beep() {
  print theme('voipcall_play_beep');
}

function theme_voipcall_play_beep() {
  $filename = drupal_get_path('module', 'voipcall') . '/sound/beep.mp3';
  header('Content-Type: audio/mpeg');
  return readfile($filename);
}

function voipcall_call_log() {
  $headers = array(
    array('data' => t('cid'), 'field' => 'cid', 'sort' => 'desc'),
    array('data' => t('start'), 'field' => 'start_time'),
    array('data' => t('user'), 'field' => 'uid'),
    array('data' => t('caller name'), 'field' => 'caller_name'),
    array('data' => t('caller number'), 'field' => 'caller_name'),
    array('data' => t('dest name'), 'field' => 'dest_name'),
    array('data' => t('dest number'), 'field' => 'dest_number'),
    array('data' => t('other')),
    ''
  );
  $sql = "SELECT cid, start_time, uid, caller_name, caller_number,dest_name,dest_number FROM {voipcall}" . tablesort_sql($headers);
  $limit = 50;
  $result = pager_query($sql, $limit);

  if ($result) {
    //your basic while loop to get the data
    while ($tmp = db_fetch_array($result)) {
      $owner = user_load($tmp['uid']);
      if (!$tmp['uid']) {
        $tmp['uid'] = t('Anonymous');
      }
      else {
        $tmp['uid'] = l($owner->name, 'user/' . $owner->name);
      }
      $tmp['start_time'] = format_date($tmp['start_time'], 'small');

      $tmp['other'] = l('See more', 'voipcall/' . $tmp['cid']);
      $data[] = $tmp;
    }
  }
  $output .= theme('table', $headers, $data);
  $output .= theme('pager', NULL, $limit, 0);
  return $output;
}

function voipcall_call_page($cid) {
  $call_data = db_fetch_array(db_query("SELECT * FROM {voipcall} WHERE cid=%d", $cid));
  foreach ($call_data as $label => $data) {
    $output .= "<div><b>" . $label . ":</b> " . $data . "</div>";
  }
  $output .= l("Go back", "admin/voip/call/log");
  return $output;
}

function voipcall_call_page_title($arg) {
  return "VoIP Call CID " . $arg;
}

function voipcall_session_log() {
  $headers = array(
    array('data' => t('sid'), 'field' => 'sid', 'sort' => 'desc'),
    array('data' => t('call_id'), 'field' => 'call_id'),
    array('data' => t('origin_number'), 'field' => 'origin_number'),
    array('data' => t('destination_number'), 'field' => 'destination_number'),
    array('data' => t('expiration_time'), 'field' => 'expiration_time'),
    array('data' => t('expiring_at'), 'field' => 'expiring_at'),
    array('data' => t('delete'), 'field' => 'delete'),
  );
  $sql = "SELECT * FROM {voipsession}" . tablesort_sql($headers);
  $limit = 50;
  $result = pager_query($sql, $limit);

  if ($result) {
    //your basic while loop to get the data
    while ($tmp = db_fetch_array($result)) {
      $tmp['expiring_at'] = format_date($tmp['expiring_at'], 'small');
      $tmp['call_id'] = l($tmp['call_id'], 'voipcall/' . $tmp['call_id']);
      $tmp['delete'] = l('Delete', 'voipsession/delete/' . $tmp['sid']);
      $data[] = $tmp;
    }
  }
  $output .= theme('table', $headers, $data);
  $output .= theme('pager', NULL, $limit, 0);
  return $output;
}

function voipcall_session_delete($sid) {
  db_query("DELETE FROM {voipsession} WHERE sid=%d", $sid);
  $output = t("Voipsession @sid deleted. ", array('@sid' => $sid));
  $output .= l('Go back', 'admin/voip/session/log');
  return $output;
}

/**
 * Implementation of hook_cron()
 */
function voipcall_cron() {
  VoipSession::deleteExpiredSessions();
}

/*Helper function to calculate WAV lenght
* Source: http://www.techaspirant.com/php-code-to-find-duration-of-an-audio-file/
*/
function voipcall_get_wav_duration($file) {
$fp = fopen($file, 'r');
$size_in_bytes = filesize($file);
fseek($fp, 20);
$rawheader = fread($fp, 16);
$header = unpack('vtype/vchannels/Vsamplerate/Vbytespersec/valignment/vbits',
$rawheader);
$sec = ceil($size_in_bytes/$header['bytespersec']);
return $sec;
}

/*Helper library to calculate MP3 length
* Source: http://www.zedwood.com/article/127/php-calculate-duration-of-mp3
*/
class mp3file
{
  protected $block;
  protected $blockpos;
  protected $blockmax;
  protected $blocksize;
  protected $fd;
  protected $bitpos;
  protected $mp3data;
  public function __construct($filename)
  {
    $this->powarr  = array(0=>1,1=>2,2=>4,3=>8,4=>16,5=>32,6=>64,7=>128);
    $this->blockmax= 1024;

    $this->mp3data = array();
    $this->mp3data['Filesize'] = filesize($filename);

    $this->fd = fopen($filename,'rb');
    $this->prefetchblock();
    $this->readmp3frame();
  }
  public function __destruct()
  {
    fclose($this->fd);
  }
  //-------------------
  public function get_metadata()
  {
    return $this->mp3data;
  }
  protected function readmp3frame()
  {
    $iscbrmp3=true;
    if ($this->startswithid3())
      $this->skipid3tag();
    else if ($this->containsvbrxing())
    {
      $this->mp3data['Encoding'] = 'VBR';
      $iscbrmp3=false;
    }
    else if ($this->startswithpk())
    {
      $this->mp3data['Encoding'] = 'Unknown';
      $iscbrmp3=false;
    }

    if ($iscbrmp3)
    {
      $i = 0;
      $max=5000;
      //look in 5000 bytes...
      //the largest framesize is 4609bytes(256kbps@8000Hz  mp3)
      for($i=0; $i<$max; $i++)
      {
        //looking for 1111 1111 111 (frame synchronization bits)
        if ($this->getnextbyte()==0xFF)
          if ($this->getnextbit() && $this->getnextbit() && $this->getnextbit())
            break;
      }
      if ($i==$max)
        $iscbrmp3=false;
    }

    if ($iscbrmp3)
    {
      $this->mp3data['Encoding'         ] = 'CBR';
      $this->mp3data['MPEG version'     ] = $this->getnextbits(2);
      $this->mp3data['Layer Description'] = $this->getnextbits(2);
      $this->mp3data['Protection Bit'   ] = $this->getnextbits(1);
      $this->mp3data['Bitrate Index'    ] = $this->getnextbits(4);
      $this->mp3data['Sampling Freq Idx'] = $this->getnextbits(2);
      $this->mp3data['Padding Bit'      ] = $this->getnextbits(1);
      $this->mp3data['Private Bit'      ] = $this->getnextbits(1);
      $this->mp3data['Channel Mode'     ] = $this->getnextbits(2);
      $this->mp3data['Mode Extension'   ] = $this->getnextbits(2);
      $this->mp3data['Copyright'        ] = $this->getnextbits(1);
      $this->mp3data['Original Media'   ] = $this->getnextbits(1);
      $this->mp3data['Emphasis'         ] = $this->getnextbits(1);
      $this->mp3data['Bitrate'          ] = mp3file::bitratelookup($this->mp3data);
      $this->mp3data['Sampling Rate'    ] = mp3file::samplelookup($this->mp3data);
      $this->mp3data['Frame Size'       ] = mp3file::getframesize($this->mp3data);
      $this->mp3data['Length'           ] = mp3file::getduration($this->mp3data,$this->tell2());
      $this->mp3data['Length mm:ss'     ] = mp3file::seconds_to_mmss($this->mp3data['Length']);

      if ($this->mp3data['Bitrate'      ]=='bad'     ||
        $this->mp3data['Bitrate'      ]=='free'    ||
        $this->mp3data['Sampling Rate']=='unknown' ||
        $this->mp3data['Frame Size'   ]=='unknown' ||
        $this->mp3data['Length'     ]=='unknown')
        $this->mp3data = array('Filesize'=>$this->mp3data['Filesize'], 'Encoding'=>'Unknown');
    }
    else
    {
      if(!isset($this->mp3data['Encoding']))
        $this->mp3data['Encoding'] = 'Unknown';
    }
  }
  protected function tell()
  {
    return ftell($this->fd);
  }
  protected function tell2()
  {
    return ftell($this->fd)-$this->blockmax +$this->blockpos-1;
  }
  protected function startswithid3()
  {
    return ($this->block[1]==73 && //I
      $this->block[2]==68 && //D
      $this->block[3]==51);  //3
  }
  protected function startswithpk()
  {
    return ($this->block[1]==80 && //P
      $this->block[2]==75);  //K
  }
  protected function containsvbrxing()
  {
    //echo "<!--".$this->block[37]." ".$this->block[38]."-->";
    //echo "<!--".$this->block[39]." ".$this->block[40]."-->";
    return(
    ($this->block[37]==88  && //X 0x58
      $this->block[38]==105 && //i 0x69
      $this->block[39]==110 && //n 0x6E
      $this->block[40]==103)   //g 0x67
      /*               ||
 ($this->block[21]==88  && //X 0x58
  $this->block[22]==105 && //i 0x69
  $this->block[23]==110 && //n 0x6E
  $this->block[24]==103)   //g 0x67*/
    );

  }
  protected function debugbytes()
  {
    for($j=0; $j<10; $j++)
    {
      for($i=0; $i<8; $i++)
      {
        if ($i==4) echo " ";
        echo $this->getnextbit();
      }
      echo "<BR>";
    }
  }
  protected function prefetchblock()
  {
    $block = fread($this->fd, $this->blockmax);
    $this->blocksize = strlen($block);
    $this->block = unpack("C*", $block);
    $this->blockpos=0;
  }
  protected function skipid3tag()
  {
    $bits=$this->getnextbits(24);//ID3
    $bits.=$this->getnextbits(24);//v.v flags

    //3 bytes 1 version byte 2 byte flags
    $arr = array();
    $arr['ID3v2 Major version'] = bindec(substr($bits,24,8));
    $arr['ID3v2 Minor version'] = bindec(substr($bits,32,8));
    $arr['ID3v2 flags'        ] = bindec(substr($bits,40,8));
    if (substr($bits,40,1)) $arr['Unsynchronisation']=true;
    if (substr($bits,41,1)) $arr['Extended header']=true;
    if (substr($bits,42,1)) $arr['Experimental indicator']=true;
    if (substr($bits,43,1)) $arr['Footer present']=true;

    $size = "";
    for($i=0; $i<4; $i++)
    {
      $this->getnextbit();//skip this bit, should be 0
      $size.= $this->getnextbits(7);
    }

    $arr['ID3v2 Tags Size']=bindec($size);//now the size is in bytes;
    if ($arr['ID3v2 Tags Size'] - $this->blockmax>0)
    {
      fseek($this->fd, $arr['ID3v2 Tags Size']+10 );
      $this->prefetchblock();
      if (isset($arr['Footer present']) && $arr['Footer present'])
      {
        for($i=0; $i<10; $i++)
          $this->getnextbyte();//10 footer bytes
      }
    }
    else
    {
      for($i=0; $i<$arr['ID3v2 Tags Size']; $i++)
        $this->getnextbyte();
    }
  }

  protected function getnextbit()
  {
    if ($this->bitpos==8)
      return false;

    $b=0;
    $whichbit = 7-$this->bitpos;
    $mult = $this->powarr[$whichbit]; //$mult = pow(2,7-$this->pos);
    $b = $this->block[$this->blockpos+1] & $mult;
    $b = $b >> $whichbit;
    $this->bitpos++;

    if ($this->bitpos==8)
    {
      $this->blockpos++;

      if ($this->blockpos==$this->blockmax) //end of block reached
      {
        $this->prefetchblock();
      }
      else if ($this->blockpos==$this->blocksize)
      {//end of short block reached (shorter than blockmax)
        return;//eof
      }

      $this->bitpos=0;
    }
    return $b;
  }
  protected function getnextbits($n=1)
  {
    $b="";
    for($i=0; $i<$n; $i++)
      $b.=$this->getnextbit();
    return $b;
  }
  protected function getnextbyte()
  {
    if ($this->blockpos>=$this->blocksize)
      return;

    $this->bitpos=0;
    $b=$this->block[$this->blockpos+1];
    $this->blockpos++;
    return $b;
  }
  //-----------------------------------------------------------------------------
  public static function is_layer1(&$mp3) { return ($mp3['Layer Description']=='11'); }
  public static function is_layer2(&$mp3) { return ($mp3['Layer Description']=='10'); }
  public static function is_layer3(&$mp3) { return ($mp3['Layer Description']=='01'); }
  public static function is_mpeg10(&$mp3)  { return ($mp3['MPEG version']=='11'); }
  public static function is_mpeg20(&$mp3)  { return ($mp3['MPEG version']=='10'); }
  public static function is_mpeg25(&$mp3)  { return ($mp3['MPEG version']=='00'); }
  public static function is_mpeg20or25(&$mp3)  { return ($mp3['MPEG version']{1}=='0'); }
  //-----------------------------------------------------------------------------
  public static function bitratelookup(&$mp3)
  {
    //bits               V1,L1  V1,L2  V1,L3  V2,L1  V2,L2&L3
    $array = array();
    $array['0000']=array('free','free','free','free','free');
    $array['0001']=array(  '32',  '32',  '32',  '32',   '8');
    $array['0010']=array(  '64',  '48',  '40',  '48',  '16');
    $array['0011']=array(  '96',  '56',  '48',  '56',  '24');
    $array['0100']=array( '128',  '64',  '56',  '64',  '32');
    $array['0101']=array( '160',  '80',  '64',  '80',  '40');
    $array['0110']=array( '192',  '96',  '80',  '96',  '48');
    $array['0111']=array( '224', '112',  '96', '112',  '56');
    $array['1000']=array( '256', '128', '112', '128',  '64');
    $array['1001']=array( '288', '160', '128', '144',  '80');
    $array['1010']=array( '320', '192', '160', '160',  '96');
    $array['1011']=array( '352', '224', '192', '176', '112');
    $array['1100']=array( '384', '256', '224', '192', '128');
    $array['1101']=array( '416', '320', '256', '224', '144');
    $array['1110']=array( '448', '384', '320', '256', '160');
    $array['1111']=array( 'bad', 'bad', 'bad', 'bad', 'bad');

    $whichcolumn=-1;
    if      (mp3file::is_mpeg10($mp3) && mp3file::is_layer1($mp3) )//V1,L1
      $whichcolumn=0;
    else if (mp3file::is_mpeg10($mp3) && mp3file::is_layer2($mp3) )//V1,L2
      $whichcolumn=1;
    else if (mp3file::is_mpeg10($mp3) && mp3file::is_layer3($mp3) )//V1,L3
      $whichcolumn=2;
    else if (mp3file::is_mpeg20or25($mp3) && mp3file::is_layer1($mp3) )//V2,L1
      $whichcolumn=3;
    else if (mp3file::is_mpeg20or25($mp3) && (mp3file::is_layer2($mp3) || mp3file::is_layer3($mp3)) )
      $whichcolumn=4;//V2,   L2||L3

    if (isset($array[$mp3['Bitrate Index']][$whichcolumn]))
      return $array[$mp3['Bitrate Index']][$whichcolumn];
    else
      return "bad";
  }
  //-----------------------------------------------------------------------------
  public static function samplelookup(&$mp3)
  {
    //bits               MPEG1   MPEG2   MPEG2.5
    $array = array();
    $array['00'] =array('44100','22050','11025');
    $array['01'] =array('48000','24000','12000');
    $array['10'] =array('32000','16000','8000');
    $array['11'] =array('res','res','res');

    $whichcolumn=-1;
    if      (mp3file::is_mpeg10($mp3))
      $whichcolumn=0;
    else if (mp3file::is_mpeg20($mp3))
      $whichcolumn=1;
    else if (mp3file::is_mpeg25($mp3))
      $whichcolumn=2;

    if (isset($array[$mp3['Sampling Freq Idx']][$whichcolumn]))
      return $array[$mp3['Sampling Freq Idx']][$whichcolumn];
    else
      return 'unknown';
  }
  //-----------------------------------------------------------------------------
  public static function getframesize(&$mp3)
  {
    if ($mp3['Sampling Rate']>0)
    {
      return  ceil((144 * $mp3['Bitrate']*1000)/$mp3['Sampling Rate']) + $mp3['Padding Bit'];
    }
    return 'unknown';
  }
  //-----------------------------------------------------------------------------
  public static function getduration(&$mp3,$startat)
  {
    if ($mp3['Bitrate']>0)
    {
      $KBps = ($mp3['Bitrate']*1000)/8;
      $datasize = ($mp3['Filesize'] - ($startat/8));
      $length = $datasize / $KBps;
      return sprintf("%d", $length);
    }
    return "unknown";
  }
  //-----------------------------------------------------------------------------
  public static function seconds_to_mmss($duration)
  {
    return sprintf("%d:%02d", ($duration /60), $duration %60 );
  }
}
