<?php

/**
 * Implementation of hook_content_default_fields().
 */
function voipcall_content_default_fields() {
  $fields = array();

  // Exported field: field_voipcall_answered_by
  $fields['voipcall-field_voipcall_answered_by'] = array(
    'field_name' => 'field_voipcall_answered_by',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_answered_by][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Answered By',
      'weight' => '4',
      'description' => 'Indicates whether the call has been answered by a machine or a human',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_call_id
  $fields['voipcall-field_voipcall_call_id'] = array(
    'field_name' => 'field_voipcall_call_id',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_call_id][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Call Id',
      'weight' => '-4',
      'description' => 'Unique identifier associated with the call.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_caller_name
  $fields['voipcall-field_voipcall_caller_name'] = array(
    'field_name' => 'field_voipcall_caller_name',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_caller_name][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Caller Name',
      'weight' => '2',
      'description' => 'The name of the caller making the call.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_caller_number
  $fields['voipcall-field_voipcall_caller_number'] = array(
    'field_name' => 'field_voipcall_caller_number',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_caller_number][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Caller Number',
      'weight' => 0,
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_check_machine
  $fields['voipcall-field_voipcall_check_machine'] = array(
    'field_name' => 'field_voipcall_check_machine',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'number_integer',
    'required' => '0',
    'multiple' => '0',
    'module' => 'number',
    'active' => '1',
    'prefix' => '',
    'suffix' => '',
    'min' => '',
    'max' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'default_value' => array(
        '0' => array(
          'value' => NULL,
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Check Machine',
      'weight' => '20',
      'description' => 'Flag indicating whether or not the call should check for answering machines.',
      'type' => 'optionwidgets_onoff',
      'module' => 'optionwidgets',
    ),
  );

  // Exported field: field_voipcall_dest_name
  $fields['voipcall-field_voipcall_dest_name'] = array(
    'field_name' => 'field_voipcall_dest_name',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_dest_name][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Destination Name',
      'weight' => '-2',
      'description' => 'Name associated with the number being called.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_dest_number
  $fields['voipcall-field_voipcall_dest_number'] = array(
    'field_name' => 'field_voipcall_dest_number',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_dest_number][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Destination Number',
      'weight' => '-3',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_direction
  $fields['voipcall-field_voipcall_direction'] = array(
    'field_name' => 'field_voipcall_direction',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_direction][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Call Direction',
      'weight' => '7',
      'description' => 'Direction of the call. Can be any of the following values: VoipScript::INBOUND, VoipScript::OUTBOUND, VoipScript::OUTBOUND_DIAL',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_duration
  $fields['voipcall-field_voipcall_duration'] = array(
    'field_name' => 'field_voipcall_duration',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_duration][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Duration',
      'weight' => '10',
      'description' => 'The duration of the call in seconds.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_end_time
  $fields['voipcall-field_voipcall_end_time'] = array(
    'field_name' => 'field_voipcall_end_time',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_end_time][0][value',
        ),
      ),
      'default_value_code' => '',
      'default_value2' => 'same',
      'default_value_code2' => '',
      'input_format' => 'm/d/Y - H:i:s',
      'input_format_custom' => '',
      'increment' => '1',
      'text_parts' => array(),
      'year_range' => '0:+1',
      'label_position' => 'above',
      'default_value_php' => NULL,
      'label' => 'End time',
      'weight' => '9',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_error_message
  $fields['voipcall-field_voipcall_error_message'] = array(
    'field_name' => 'field_voipcall_error_message',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_error_message][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Error Message',
      'weight' => '11',
      'description' => 'Eventual error message associated with the call.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_hangup_reason
  $fields['voipcall-field_voipcall_hangup_reason'] = array(
    'field_name' => 'field_voipcall_hangup_reason',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_hangup_reason][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Hangup Reason',
      'weight' => '14',
      'description' => 'Stores a constant with reason for the call hangup. NULL otherwise.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_hangup_script
  $fields['voipcall-field_voipcall_hangup_script'] = array(
    'field_name' => 'field_voipcall_hangup_script',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_hangup_script][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Hangup Script Name',
      'weight' => '13',
      'description' => 'Name of the script that should be evoked whenever the system receives a "hangup-related event" leading to call status such as VoipScript::ERROR, VoipScript::NOT_CALLED, VoipScript::DIALING, VoipScript::NO_ANSWER, VoipScript::BUSY, VoipScript::INVALID, VoipScript::MACHINE_HANGUP, VoipScript::COMPLETED.  The only events that do not activate the hangup script are the ones that lead to the following call status: VoipScript::ANSWERED, VoipScript::ANSWERED_MACHINE, VoipScript::ANSWERED_HUMAN.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_script
  $fields['voipcall-field_voipcall_script'] = array(
    'field_name' => 'field_voipcall_script',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => '10',
      'size' => 60,
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_script][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Script',
      'weight' => '12',
      'description' => 'The script associated with the call.',
      'type' => 'text_textarea',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_sms_status
  $fields['voipcall-field_voipcall_sms_status'] = array(
    'field_name' => 'field_voipcall_sms_status',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_sms_status][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'SMS Status',
      'weight' => '5',
      'description' => 'Status of the SMS transmission.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_source
  $fields['voipcall-field_voipcall_source'] = array(
    'field_name' => 'field_voipcall_source',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_source][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'rows' => 5,
      'size' => '60',
      'label' => 'Call Source',
      'weight' => '6',
      'description' => 'The server that originated the call, i.e., \'drupal\', \'asterisk\', \'twilio\', etc.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_voipcall_start_time
  $fields['voipcall-field_voipcall_start_time'] = array(
    'field_name' => 'field_voipcall_start_time',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'number_integer',
    'required' => '0',
    'multiple' => '0',
    'module' => 'number',
    'active' => '1',
    'prefix' => '',
    'suffix' => '',
    'min' => '',
    'max' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_start_time][0][value',
        ),
      ),
      'default_value_code' => '',
      'default_value2' => 'same',
      'default_value_code2' => '',
      'input_format' => 'm/d/Y - H:i:s',
      'input_format_custom' => '',
      'increment' => '1',
      'text_parts' => array(),
      'year_range' => '0:+1',
      'label_position' => 'above',
      'default_value_php' => NULL,
      'label' => 'Start time',
      'weight' => '8',
      'description' => '',
      'type' => 'number',
      'module' => 'number',
    ),
  );

  // Exported field: field_voipcall_status
  $fields['voipcall-field_voipcall_status'] = array(
    'field_name' => 'field_voipcall_status',
    'type_name' => 'voipcall',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_voipcall_status][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Call Status',
      'weight' => '3',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Answered By');
  t('Call Direction');
  t('Call Id');
  t('Call Source');
  t('Call Status');
  t('Caller Name');
  t('Caller Number');
  t('Check Machine');
  t('Destination Name');
  t('Destination Number');
  t('Duration');
  t('End time');
  t('Error Message');
  t('Hangup Reason');
  t('Hangup Script Name');
  t('SMS Status');
  t('Script');
  t('Start time');

  return $fields;
}
